// Automatically generated by flapigen
package com.example.rustapplication.lib;


public final class Inputs {

    public Inputs(long first, long second) {
        mNativeObj = init(first, second);
    }
    private static native long init(long first, long second);

    public final long addition() {
        long ret = do_addition(mNativeObj);

        return ret;
    }
    private static native long do_addition(long self);

    public final long subtraction() {
        long ret = do_subtraction(mNativeObj);

        return ret;
    }
    private static native long do_subtraction(long self);

    public final long multiplication() {
        long ret = do_multiplication(mNativeObj);

        return ret;
    }
    private static native long do_multiplication(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Inputs(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}